### ISSUE TITLE
GLQuake

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#10]
GLQuake ~ Missing Hombrews
https://psp.scenebeta.com/noticia/glquake-psp
![IMG_20210407_180337](https://user-images.githubusercontent.com/81209454/113866992-9b9f5d80-97cb-11eb-85a1-8740ba733135.jpg)

**Comment by pierrelouys** [comment]
It could be the same as this:

https://archive.org/details/psp-quake-1-v-11.0-slim.-7z

I'm not sure. Will have to look into this.

**Comment by pierrelouys** [comment]
They seem to be the same, after all. Removed from the list.
