### ISSUE TITLE
gpSP/ gpSP mod Src.

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#12]
> Source Code

- gpSP mod Source Code
https://github.com/BASLQC/gPSP-mod

- gpSP
https://github.com/BASLQC/gPSP

- SNES9X Euphoria
https://github.com/BASLQC/snes9x-euphoria

- Nesterj
https://github.com/rinrin-/NesterJ_AoEX_R3

- MasterBoy
https://github.com/wodim/MasterBoy

- pboot.pbp editor
https://github.com/173210/pboot

- Chip8 psp
https://github.com/stacksta/chip8_psp

**Comment by pierrelouys** [comment]
We don't generally archive source code if it is already on GitHub, as it would be redundant.

**Comment by ptnnx** [comment]
Ok, I Understand.
