### ISSUE TITLE
ADD+[NEW] Info V2

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#14]
> 
**https://github.com/PSP-Archive/docs/blob/main/code-archive/other-projects.md**
**Added files**

- potator psp
 https://github.com/infval/potator-psp-akop

- scummvm psp
https://github.com/rsn8887/scummvm/releases/tag/2.1.0git-rsn8887.30

- vice psp
https://github.com/rsn8887/pspvice

- Chocolate Doom
https://github.com/mwpenny/chocolate-doom-psp

- cmfile manager
https://github.com/joel16/CMFileManager-PSP

- blind jump portable
https://github.com/evanbowman/blind-jump-portable

- Spelunky
https://github.com/dbeef/spelunky-psp

- lua player+
https://github.com/Rinnegatamante/lua-player-plus

- wolf 3d
https://github.com/BenMcLean/Wolf3D-PSP

- opentri
https://github.com/albe/openTri

- xlab
https://github.com/xfacter/xlab

- psp mciso
https://github.com/sindastra/psp-mciso

- qpspmanager
https://github.com/CalmCreative/qpspmanager

- pbpcombiner
https://github.com/remixer-dec/PBPCombiner

----------------------------------
**Can be Add**
- openbor psp 
https://github.com/DCurrent/openbor

- MegaZeux psp
https://github.com/AliceLR/megazeux/

- PlutoBoy
https://github.com/RossMeikleham/PlutoBoy

- Open Lara
https://github.com/XProger/OpenLara/releases/tag/20180524

- SM64 port psp
https://github.com/z2442/sm64-port

- Aleph one
https://github.com/Aleph-One-Marathon/alephone-psp

---------------------------------------------
> Archive.org

**Comment by pierrelouys** [comment]
All added, except for:

- psp mciso
- https://github.com/sindastra/psp-mciso
- qpspmanager
-- https://github.com/CalmCreative/qpspmanager
- pbpcombiner
-- https://github.com/remixer-dec/PBPCombiner

Interesting, but not PSP homebrews.

- https://github.com/evanbowman/blind-jump-portable
-- It says a PSP release is available, but I cannot find one.

Updates: https://github.com/PSP-Archive/docs/commit/31fee7a690d27905d259d06c3207c37362a946a4

**Comment by ptnnx** [comment]
https://github.com/evanbowman/blind-jump-portable

I did not find anywhere, I saw all the versions. So I think it will only have its source code or it will work in PSP in future maybe.

**Comment by pierrelouys** [comment]
Will add Blind Jump when a PSP version is released. Closing for now.

**Comment by ptnnx** [comment]
Ok
