### ISSUE TITLE
Old Strange ! info V3

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#16]
**Info***
**How to play neogeo games on your PSP FAT**
https://gist.github.com/aymerick/a47c2d04ebf319bcf3ba

**Old Hombrews 2005 - Sites**

http://adventpspsite.blogspot.com/2007/10/?m=1

http://new0rder.blogspot.com/?m=1

http://psphacks.blogspot.com/?m=1

https://dsync.blogspot.com/2014/04/a-complete-tutorial-to-install-homebrew.html?m=1

http://fixmypsptoo.blogspot.com/2010/05/play-nintendo-ds-games-on-your-psp-ds.html?m=1

http://pspalmaster.blogspot.com/2009/02/pspmastermind-released.html?m=1

https://www.neoseeker.com/forums/23172/t1397810-updated-super-mega-ultimate-homebrew-custom-firmware-thread/

http://fjmhomebrew.com/

http://jakvanz.blogspot.com/?m=1

https://musicthing.blogspot.com/2005/07/pspkick-homebrew-drum-machine-for-psp.html?m=1

http://thepsptribune.blogspot.com/?m=1

http://portable-psp.blogspot.com/?m=1

http://ultimate-psp-hacks.blogspot.com/2011/03/psp-lcfw-for-psp-3000s-psp-gos-and.html?m=1

**NOTE:Some link are not working only for info**

**Comment by pierrelouys** [comment]
You seem to have quite a lot of stuff to contribute. I have granted you edit access to the repo - use it wisely.

**Comment by RDX00** [comment]
Ok, I an Working
