### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#17]
I have done general editing. How do you feel You give me opinion. Tell me in more detail about which subject you should pay more attention to. Thank you for adding your repo to me. I will contribute to it.
Tnx.

**Comment by pierrelouys** [comment]
You are adding lots of missing repos - some I didn't know existed, so it's pretty great. If you want to discuss the project further, there is the #preservation channel on the PSP Discord: https://discord.gg/fExU55Pk

**Comment by ptnnx** [comment]
Thank you very much. I will help you by adding it.
