### ISSUE TITLE
ADD+[NEW] ! Info V4

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#18]
- Monkey64
https://github.com/TheMrIron2/Monkey64
- Golden Eye
https://github.com/TheMrIron2/goldeneye-psp
- Cannonball PSP
https://github.com/TheMrIron2/cannonball-PSP
- hnefatafl
https://github.com/TheMrIron2/hnefatafl-psp
- Emblem of Fire
https://github.com/TheMrIron2/Emblem-of-Fire
- Project Enigma
https://github.com/TheMrIron2/project-enigma
- Perfect Dark Reloaded
https://github.com/TheMrIron2/Perfect-Dark-Reloaded

**Comment by pierrelouys** [comment]
You have edit access now - feel free to add them 😉
