### ISSUE TITLE
[Suggestion/Future Request] Akop Karapetyan +

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#2]
I want to tell you that you have taken an old version of some Emulators of Akpo Karapetyan. I want you to add new versions of Akop emu.
Link
* https://wololo.net/talk/viewtopic.php?f=47&t=50039 Atari800 4.2.0
Upload a new version Atari800 on Archive.org
* https://wololo.net/talk/viewtopic.php?f=47&t=49644 Caprice32 4.2.0.3
* https://wololo.net/talk/viewtopic.php?f=47&t=49633 fMSX 5.4.2
-------------------------------------------
» Here Atari800 Old Ver 2.1.0.1

![Screenshot_2021-04-06-17-11-05-63](https://user-images.githubusercontent.com/81209454/113707375-704e3d00-96fd-11eb-89fb-27ccf7755740.jpg)

» Here Atari800 New Ver 4.2.0

![Screenshot_2021-04-06-17-11-41-06](https://user-images.githubusercontent.com/81209454/113707502-9f64ae80-96fd-11eb-82f6-c9a49a87c6cf.jpg)

____________________________
» Here Caprice32 Old Ver 4.2.0.2

![Screenshot_2021-04-06-17-12-34-83](https://user-images.githubusercontent.com/81209454/113707557-b3101500-96fd-11eb-9b0b-c7badb66dc46.jpg)

» Here Caprice32 New Ver 4.2.0.3

![Screenshot_2021-04-06-17-12-20-15](https://user-images.githubusercontent.com/81209454/113707772-05e9cc80-96fe-11eb-97ae-d0d372e3296f.jpg)
______________________________
» Here fMSX Old Ver 3.5.41

![Screenshot_2021-04-06-17-16-32-95](https://user-images.githubusercontent.com/81209454/113707905-30d42080-96fe-11eb-9dbd-7dafedb9240e.jpg)

» Here fMSX New Ver 5.4.2

![Screenshot_2021-04-06-17-16-10-91](https://user-images.githubusercontent.com/81209454/113707983-5103df80-96fe-11eb-98e6-98f037bb5530.jpg)

**I suggestion Upload a Top Emulators New Version.**

**Comment by pierrelouys** [comment]
I'm unfamiliar with those builds, I will look into the code to try and figure out if any actual improvements were made - lots of times, when an unrelated, unknown dev claimed to have improved a more famous project, the only real change they made was increasing the version number... but in this case the source is there, so it should be possible to go through the changes.

**Comment by ptnnx** [comment]
Ok
You Can Check it.

**Comment by pierrelouys** [comment]
Hard to judge the quality of the changes, but they're not hex edits, and there were plenty of changes - at least for the one emu that had source available.
Updated:
https://archive.org/details/fmsxpsp.7z
https://archive.org/details/cpc-300750-00000
https://archive.org/details/atar-01248-00000
