### ISSUE TITLE
I find eSwan 0.8 + OSwan Source Code

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#23]
[eSwan08.zip](https://github.com/PSP-Archive/docs/files/6330638/eSwan08.zip)

I found this source a official site by e
Eswan+Oswan (inclusive) source
You can check it.

**Comment by ptnnx** [comment]
And also
![IMG_20210418_124051](https://user-images.githubusercontent.com/81209454/115137368-5d176780-a043-11eb-8093-884865ed8bde.jpg)

Nicky (Double) file Check it.

**Comment by pierrelouys** [comment]
- [x] Nicky (Double) file Check it.

![grafik](https://user-images.githubusercontent.com/75588890/115138508-eb342380-a02c-11eb-920f-883612a06ab0.png)

Not eSwan.

**Comment by RDX00** [comment]
Why did you block me Forgive me if I have made a mistake. I will not bother you from now on.
Sorry
