### ISSUE TITLE
Useful Resources

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#26]
**Maybe Useful**

https://web.archive.org/web/*/pspadventure.com/* - grab it psp hombrews etc.

https://web.archive.org/web/*/http://takka.tfact.net/blog/*  - you can grab it.this site.

https://web.archive.org/web/20181116215159/http://psp.me.land.to/ - Working links

https://web.archive.org/web/*/pspthemes86.blog72.fc2.com/* - Collection Themes and various

- various hombrews game
http://gameandpsp.jugem.jp/?eid=168#gsc.tab=0

- best site psp hombrews games
http://cloud312.ldblog.jp/archives/50446573.html

**Themes**

[PSP Themes (jpn).zip](https://github.com/PSP-Archive/docs/files/6331588/PSP.Themes.jpn.zip)

11000+ Themes
https://web.archive.org/web/*/pspthemes.org/*

Theme
https://web.archive.org/web/*/ux.getuploader.com/*

Psp hombrews etc.+
https://web.archive.org/web/*/ux.getuploader.com/*

**Comment by pierrelouys** [comment]
- [x]     Taikopsp
- already uploaded
- [x]     otawa browser and source code
- already uploaded
- [x]     mario fusion
- already uploaded
- [x]     mario mosochism
- already uploaded
- [x]     snik's mario demo
- already uploaded
- [x]     Battle fantasy
- already uploaded
- [x]     legend of zelda trilogy pack
- already uploaded
- [x]     bombastic
- already uploaded
- [x]     2050 the last island demo
- already uploaded
- [x]     jumping rectangle
- already uploaded
- [x]     soyobon action game
- already uploaded
- [x]     kene-touhou-mohofu
- already uploaded
- [ ]     cxmb installer
- flasher, we don't keep those
- [ ]     pspstate menu
- https://hiroi01.com/?p=prx#states_menu_pict
- download link is dead
- [x]     newton war
- already uploaded
- [x]     megaman netnavi.exe
- already uploaded
- [x]     Touhou Yusou v0.81
- new, uploaded here: https://archive.org/details/thp.7z 
- [x]     kys tester
-  new, uploaded here: https://archive.org/details/keys-tester-v-41.7z
- [x]     sqrxz
- already uploaded
- [x]     pspdungeon : assault run
- already uploaded
- [x]     tibiapsp rpg
- already uploaded
- [x]     super smash bros psp
- already uploaded
- [x]     supermario portable
- already uploaded
- [x]     netfront internet browser
- already uploaded
- [x]     psp revolution
- already uploaded
- [x]     psp iso tool
- already uploaded
- [x]     psp manga fx
- already uploaded
- [ ]     calcus psp
-    https://web.archive.org/web/20130812214332/http://www.pspstation.org/scene-psp-71/calcula-psp-v1-5-a-26576/ 
- download link is broken
- [x]     psp mario new world
- already uploaded
- [ ]     dorakz
- possibly a flasher? seems to change config files
- [x]     GDP
- already uploaded

- Please check the [xml list](https://archive.org/advancedsearch.php?q=collection%3Apsp-homebrew-library&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=description&fl[]=subject&fl[]=version&fl[]=date&fl[]=language&sort[]=titleSorter+asc&rows=10000&page=1&output=xml) before suggesting new uploads. They might not actually be new.

**Comment by ptnnx** [comment]
Ok i Check XML will upload it.

**Comment by ptnnx** [comment]
**NOTE : I don't know it's items Useful or not, but you can check it?**



**Pfile v0.02**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/pfile_v002.zip (bin)
-https://github.com/hiroi01/pfile-prx (src)
+ With prx common Library
-https://code.google.com/archive/p/prx-common-libraries/downloads

**mhp3plus Ver.0.3**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/mhp3plus_for_660.zip (bin)
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/mhp3plus_for_660_src.zip (src)

**ptextviewer v1.03 ~ 2.00beta6**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/ptextviewer_v103.zip (1.03)
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/ptextviewer_v200beta6.zip (2.00b6)

**pprefx prx**
-https://wololo.net/talk/viewtopic.php?f=26&t=6580

**PspStatesMenu_Pict ver. 1.06-3** + source
https://hiroi01.com/dl.php/mbkDb3c4/IpMo/states_menu_pict_v106-3.zip

**pergame_custom ver. 1.01**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/pergame_custom_v101.zip

**gnpcheater v1.01**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/gnpcheater_v101.zip (bin)
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/gnpcheater_v101_src.zip (src)

**bright3.prx** + source
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/bright3_v003.zip

**BatteryPercentCtrl.prx**
-https://hiroi01.com/dl.php/mbkDb3c4/IpMo/BatteryPercentCtrl.zip
