### ISSUE TITLE
Minor fix?

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#27]
## Archive.org minor issue

- 1.**pokemini 0.5.4 (old) preview screen shot**

![IMG_20210420_093911](https://user-images.githubusercontent.com/81209454/115337826-56adfa80-a1bf-11eb-8c92-f217d0aa5157.jpg)

**Update new screen shot**
![Screenshot_2021-04-20-08-41-03-69](https://user-images.githubusercontent.com/81209454/115337907-78a77d00-a1bf-11eb-8ca5-4f250c3b2862.jpg)
__________________________
- 2. **Virtual jaguar port (pjag 0.001)** update version info and name
![IMG_20210420_093901](https://user-images.githubusercontent.com/81209454/115338035-b1475680-a1bf-11eb-8204-b4f83559301b.jpg)
____________________________
- 3. **Bochs for psp 0.1** add version info
![IMG_20210420_093828](https://user-images.githubusercontent.com/81209454/115338222-fe2b2d00-a1bf-11eb-823f-c5345ba81be6.jpg)

--Check link--
[Bochs 1.0](https://gbatemp.net/download/bochs-x86-emulator.9872/)
_____________________
- 4. **PSPadrive release 1** add version info
![IMG_20210420_093802](https://user-images.githubusercontent.com/81209454/115338363-4f3b2100-a1c0-11eb-9bd5-9d5a49eb3a3e.jpg)

--check link--
[PSPadrive release 1](http://psp-news.dcemu.co.uk/emulators-for-psp-20813.html)
___________________
- 5. **Vba for psp** by Anonymous Japanese coder** update info
![IMG_20210420_093602](https://user-images.githubusercontent.com/81209454/115338562-ae009a80-a1c0-11eb-9545-dc9045d12dc0.jpg)
____________________
- 6. **Unofficial Nesterj** add full name of auther**
![IMG_20210420_104404](https://user-images.githubusercontent.com/81209454/115340983-5e709d80-a1c5-11eb-9e83-531df26e192b.jpg)
And check version info
![iMarkup_20210420_120211](https://user-images.githubusercontent.com/81209454/115348511-536f3a80-a1d0-11eb-993b-2a21a070a909.jpg)

____________________
- 7. **gpSP-j** add auther info
![IMG_20210420_103541](https://user-images.githubusercontent.com/81209454/115340664-beb30f80-a1c4-11eb-9e89-19488f08a845.jpg)

______________________
-8. **TempGBA** add auther info
![iMarkup_20210420_095228](https://user-images.githubusercontent.com/81209454/115340598-988d6f80-a1c4-11eb-8fdf-ed5d215d27b9.jpg)
![iMarkup_20210420_093713](https://user-images.githubusercontent.com/81209454/115340645-b5c23e00-a1c4-11eb-99ce-cb1ab7d74810.jpg)
_________________________
- 9.**fba LB** update auther info
![IMG_20210420_094618](https://user-images.githubusercontent.com/81209454/115340910-3a14c100-a1c5-11eb-80d1-6c778c0d1236.jpg)
___________________________
- 10.**PSP-gnuboy release 1** update version info
![iMarkup_20210420_105045](https://user-images.githubusercontent.com/81209454/115341454-48171180-a1c6-11eb-86b3-4abe482e638a.jpg)

--Check link--
[PSP-gnuboy release 1](http://psp-news.dcemu.co.uk/emulators-for-psp-20814.html)
____________________________
- 11.**Red Dragon** Update version info
![iMarkup_20210420_105304](https://user-images.githubusercontent.com/81209454/115341666-a2b06d80-a1c6-11eb-83ce-58c9cba744bf.jpg)
___________________________
- 12.**Nester j aoex r3** i found r3 SP version idont know who's new version? You check please.
![iMarkup_20210420_105640](https://user-images.githubusercontent.com/81209454/115341956-18b4d480-a1c7-11eb-9417-5b8106e4293a.jpg)

**Link**
[Nesterj Aoex r3 SP](https://wololo.net/talk/viewtopic.php?t=38758)

And i found 
[Nesterj 3D](https://wololo.net/downloads/index.php/download/1242)

_____________________
- 13. **Tommy's pspvba+ source** can be add
![IMG_20210420_094017](https://user-images.githubusercontent.com/81209454/115342522-0a1aed00-a1c8-11eb-9ab3-c3c33b15ad16.jpg)

[tommyspspvba0.1.zip](https://github.com/PSP-Archive/docs/files/6340878/tommyspspvba0.1.zip)

--check link--
[Tommy's VBA 0.1](http://psp-news.dcemu.co.uk/emulators-for-psp-29954.html)
_________________________________
- 14. **Nesterj 1.12+0.61 RM+source** can be add
![IMG_20210420_094030](https://user-images.githubusercontent.com/81209454/115342615-29b21580-a1c8-11eb-9a2c-2309d4ef4c8e.jpg)

[nesterJ_1.12_Plus_0.61_RM_rewind_mirror_mod.zip](https://github.com/PSP-Archive/docs/files/6340875/nesterJ_1.12_Plus_0.61_RM_rewind_mirror_mod.zip)

--check link--
[Nesterj+](http://psp-news.dcemu.co.uk/nesterj-1-12-plus-0-61-rm-nes-emulator-for-psp-289914.html)
________________________
- 15.**Desmume+source**
Update this version link below
[DeSmuME fix.zip](https://github.com/PSP-Archive/docs/files/6340866/DeSmuME.fix.zip)

Old sources
[DeSmuME20070725.zip](https://github.com/PSP-Archive/docs/files/6340871/DeSmuME20070725.zip)
___________________
- 16.**nullDC update version tnx xiro**
[EBOOT.PBP.zip](https://github.com/PSP-Archive/docs/files/6340919/EBOOT.PBP.zip)
____________________
- 17**Dosbox psp 0.73** can you find this version
![IMG_20210420_093848](https://user-images.githubusercontent.com/81209454/115344054-6848cf80-a1ca-11eb-83fe-07014d7da9e1.jpg)

______________________
- 18.**frotz-psp 1.0** update version info
![IMG_20210420_112252](https://user-images.githubusercontent.com/81209454/115344345-e73e0800-a1ca-11eb-887e-d4bd9de27727.jpg)
![IMG_20210420_112308](https://user-images.githubusercontent.com/81209454/115344363-eefdac80-a1ca-11eb-8ff8-c05d93e88d29.jpg)
__________________
- 22.**source code**

[27546-psplegacy_r4.zip](https://github.com/PSP-Archive/docs/files/6341001/27546-psplegacy_r4.zip)
-psplegacy source

[27544-15134_pspdoomv1.4.zip](https://github.com/PSP-Archive/docs/files/6341005/27544-15134_pspdoomv1.4.zip)
-pspdoom source

https://www.brewology.com/downloads/download.php?id=11724&mcid=1
-uo nesterj rm

[8150-uoPicodrive135bR_by_davex.zip](https://github.com/PSP-Archive/docs/files/6341008/8150-uoPicodrive135bR_by_davex.zip)
-uo PicoDrive 1.35b davex source

[Unofficial_SMSPlusPSP123_RM_by_davex.zip](https://github.com/PSP-Archive/docs/files/6341016/Unofficial_SMSPlusPSP123_RM_by_davex.zip)
-uo smsplus davex source
_________________________
- 23.**psp2600** add preview

![IMG_20210420_115455](https://user-images.githubusercontent.com/81209454/115347690-574e8d00-a1cf-11eb-82c8-c9c3c0fe9913.jpg)
ADD
![Screenshot_2021-04-20-11-54-26-32](https://user-images.githubusercontent.com/81209454/115347697-59b0e700-a1cf-11eb-9360-eabe01c06995.jpg)

__________________
- 24.**DSonPSP** Beta 7 rev Kayliah Edition add update info
![iMarkup_20210420_121957](https://user-images.githubusercontent.com/81209454/115350435-bbbf1b80-a1d2-11eb-938e-255d6ca75b1b.jpg)

And add preview screenshot
![20110612190425](https://user-images.githubusercontent.com/81209454/115350972-5ddf0380-a1d3-11eb-9a24-2003b314d3a1.jpg)

_________________________
- 25.**little john PSP** https://archive.org/details/not-working-psp 
- You add on not working files
https://psp.brewology.com/downloads/download.php?id=6169&mcid=1
Add on not working file.

**Comment by pierrelouys** [comment]
- Dosbox psp 0.73: impossible to find, I think it's lost forever.
- Nesterj 3D: uploaded here: https://archive.org/details/nester-j-3-d-a.-7z

**Comment by ptnnx** [comment]
Tnx
For suggestions

**Comment by ptnnx** [comment]
And you can check my some details please
