### ISSUE TITLE
Code!

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#28]
**source code available?** **Add on Repositories**

-xtreamRace
https://sourceforge.net/projects/xtreamrace/

-cueplaypsp
https://sourceforge.net/projects/cueplayerpsp/

-pspkobo
https://sourceforge.net/projects/pspkobo/

-psphotel
https://sourceforge.net/projects/psphotel/

-pspcube
https://sourceforge.net/projects/psp-cube/

-zombie search psp
https://sourceforge.net/projects/zombie-search/

-dsmb
https://sourceforge.net/projects/dsmb/

-magicball
https://sourceforge.net/projects/magicbowl/

-psp 2d tank
https://sourceforge.net/projects/psp2dtanks/

-freevial
https://sourceforge.net/projects/freevial/

-SIGUEMEforPSP
https://sourceforge.net/projects/siguemeforpsp/

-gravity power ll
https://sourceforge.net/projects/gp2/

-sbacc portable
https://sourceforge.net/projects/sabaccportable/files/

-psp media library
https://sourceforge.net/projects/pspmedialibrary/

-monkeyX64
https://sourceforge.net/p/monkeyx64/code/HEAD/tree/

-vmines
https://sourceforge.net/projects/vmines/

-alphabase psp
https://sourceforge.net/projects/alphabasepsp/files/

-box4psp
https://sourceforge.net/projects/pspconsole/files/

-zelda onilink begins
https://sourceforge.net/projects/zeldaolb/

-Zelda - Return of the Hylian for the PSP
https://sourceforge.net/projects/zelda-roth-psp/

-zelda navis quest
https://sourceforge.net/projects/zeldansq/

-zelda time
https://sourceforge.net/projects/zeldat3/

-usp
https://sourceforge.net/projects/unrealspeccyp/

-pspmario new world
https://sourceforge.net/projects/projectd2/

-clouddy psp
https://sourceforge.net/projects/clouddypsp/

-psmails
https://sourceforge.net/projects/psmails/

-supertux
https://sourceforge.net/projects/supertuxpsp/

-warcraft psp
https://sourceforge.net/projects/warcraftpsp/

-bahamut
https://sourceforge.net/projects/bahamut/

-openpsp
https://sourceforge.net/projects/openpsp/

-nand currency
https://sourceforge.net/projects/nandcurrency/files/

-shootzemall
https://sourceforge.net/p/shootzemall/code/HEAD/tree/

-pspmetronome
https://sourceforge.net/projects/pspmetronome/

-pspkanji
https://sourceforge.net/projects/pspkanji/

-pspvorbo
https://sourceforge.net/projects/pspvorbo/

-pspposte
https://sourceforge.net/projects/psposte/

-pspux
https://sourceforge.net/projects/pspux/

-boost4psp
https://sourceforge.net/projects/boost4psp/

-psppool
https://sourceforge.net/projects/psp-pool/

-awaker
https://sourceforge.net/projects/awaker/

-defence station
https://sourceforge.net/projects/dsp/

-simpeamp
https://sourceforge.net/p/simpleamp/code/HEAD/tree/

-psplibri
https://sourceforge.net/projects/psplibri/

-puzzle slider
https://sourceforge.net/projects/puzzleslider/

-pspradio
https://sourceforge.net/projects/pspradio/

-spindizzy
https://sourceforge.net/p/spindizzy/code/HEAD/tree/

-psprpg
https://sourceforge.net/p/psprpg/code/HEAD/tree/

-pspagenda
https://sourceforge.net/projects/psp-agenda/

-pspted
https://sourceforge.net/projects/pspted/

-pdf2psp
https://sourceforge.net/projects/pdf2psp/

-freepsp game
https://sourceforge.net/projects/freepspgames/

-neturbia
https://sourceforge.net/p/neturbia/code/HEAD/tree/

-gunna blade
https://sourceforge.net/p/gunnablade3d/code/HEAD/tree/

-pacmonster
https://sourceforge.net/p/pac-monster/code/HEAD/tree/

-mplayer wm
https://sourceforge.net/projects/mplayer-ww/

-themcw base
https://sourceforge.net/p/themcwbase/code/HEAD/tree/

**Comment by pierrelouys** [comment]
Only checking for binaries, no patience to mass transfer code from Sourceforge right now tbh:

- [x] xtreamRace
no binary available, we'd need someone to compile it first - assuming it was ever completed

- [x] cueplaypsp
Already uploaded: https://archive.org/details/cueplayerpsp-ogg.7z

- [x] pspkobo
Already uploaded: https://archive.org/details/pspkobo-v-1-21.7z

- [x] psphotel
Html scripts.

- [x] pspcube
No binary.

- [x] zombie search psp
New: https://archive.org/details/zombie-search-alpha-ver-3.5.7z

- [x] dsmb
No binary.

- [x] magicball
Already uploaded: https://archive.org/details/magic-bowl-v-1-0

- [x] psp 2d tank
New: https://archive.org/details/psp-2-dtanks.-7z

- [x] freevial
Already uploaded: https://archive.org/details/proypsp.7z

- [x] SIGUEMEforPSP
New: https://archive.org/details/siguemev-1.0-a.-7z

- [x] gravity power ll
PC game. A PSP port was attempted but abandoned: https://sourceforge.net/p/gp2/git/ci/29a94f4baf6909dcca78336373ae7be1a7dba351/

- [x] sbacc portable
Updated: https://archive.org/details/sabacc-basics-0.7.0a.-7z

- [x] psp media library
No binary.

- [x] monkeyX64
No binary, no real updates compared to 'old' Monkey64.

- [x] vmines
Already uploaded: https://archive.org/details/vmines.-7z

- [x] alphabase psp
Lua script error. Broken?

- [x] box4psp
No binary.

- [x] zelda onilink begins
Already uploaded: https://archive.org/details/zelda-olb-v-1.7z

- [x] Zelda - Return of the Hylian for the PSP
Already uploaded: https://archive.org/details/zelda-roth.-7z

- [x] zelda navis quest
Already uploaded: https://archive.org/details/zelda-nsq.-7z

- [x] zelda time
Already uploaded: https://archive.org/details/zelda-t-3-v-3.7z

- [x] usp
Already uploaded: https://archive.org/details/usp_0.0.62.7z

- [x] pspmario new world
Already uploaded: https://archive.org/details/pspmario-the-new-worldsv-003.7z

- [x] clouddy psp
Interesting, but not a homebrew.

- [x] psmails
No binary.

- [x] supertux
Already uploaded: https://archive.org/details/supertux-0.1.3-psp.-7z

- [ ] warcraft psp
Needs a check on real HW

- [x] bahamut
No binary.

- [x] openpsp
No binary.

- [x] nand currency
New: https://archive.org/details/nand-currency-v-1.4.7z

- [x] shootzemall
No binary.

- [x] pspmetronome
Already uploaded: https://archive.org/details/pspmetronome-0.1a-EBOOT.7z

- [x] pspkanji
Already uploaded: https://archive.org/details/psp-kanjiv-2-3.7z

- [x] pspvorbo
New: https://archive.org/details/revorbinstall.7z

- [x] pspposte
Already uploaded: https://archive.org/details/psposte-beta-7-fw-4x.-7z

- [ ] pspux
https://sourceforge.net/projects/pspux/

- [ ] boost4psp
https://sourceforge.net/projects/boost4psp/

- [x] psppool
No binary.

- [x] awaker
Already uploaded: https://archive.org/details/awaker.-7z

- [x] defence station
Already uploaded: https://archive.org/details/dsp.7z

- [x] simpeamp
No binary.

- [x] psplibri
Python script.

- [x] puzzle slider
New: https://archive.org/details/puzzleslider_0.1alpha.7z

- [x] pspradio
Already uploaded: https://archive.org/details/pspradio-1.18.1400.7z

- [x] spindizzy
No binary.

- [x] psprpg
No binary.

- [x] pspagenda
No binary or code.

- [x] pspted
New: https://archive.org/details/pspted-0.0.3.7z

- [x] pdf2psp
Mac app?

- [x] freepsp game
No binary or code.

- [x] neturbia
No binary.

- [x] gunna blade
No binary.

- [x] pacmonster
No binary.

- [x] mplayer wm
PC app?

- [x] themcw base
No binary.

**Comment by ptnnx** [comment]
Blind jump portable source
https://github.com/evanbowman/blind-jump-portable/blob/master/source/platform/psp/psp_platform.cpp
