### ISSUE TITLE
Atari7800 request

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#3]
* https://atariage.com/forums/topic/156322-psp7800-version-14/ Atari7800 New Version 1.4.0

» Here old Atari7800 1.2  version
![Screenshot_2021-04-06-17-52-08-72](https://user-images.githubusercontent.com/81209454/113710563-7fcf8500-9701-11eb-8647-0d11599cc7ac.jpg)
‡ Uploade new Atari7800 1.4 version

**Comment by pierrelouys** [comment]
Version 1.4 is, in my experience at least, a poorly done hack job of the original code. Save state support is very spotty - a number of features are broken... unfortunately, a number of unscrupulous people went around claiming to have improved this or that homebrew, without doing any useful work at all (MasterBoy 2.10 would be a prime example).
