### ISSUE TITLE
I found some Chines Homebrew s

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#38]
I think some chinese missing Homebrew s
I don't know but you try it and find it
[Lnk](https://boxer.baidu.com/scheme?source=1023865r&channel=1023871a&p1=1023871a&p2=&p3=1023865r&tokenData=%257B%2522activity_id%2522%253A%2522227%2522%252C%2522url%2522%253A%2522AZQtr4jkpf90T3X9QMWVLF1bkeV4LXxD%252Fpages%252Flemma%252Flemma%253FlemmaTitle%253DNGE2%2526lemmaId%253D2679125%2526fr%253DinvokeBox%2526%25257B%252522from%252522%25253A%2525221023865r%252522%25252C%252522channel%252522%25253A%2525221023871a%252522%25252C%252522backwardURL%252522%25253A%252522https%25253A%25252F%25252Fbaike.baidu.com%25252Fitem%25252FNGE2%252522%25257D%2522%257D)

**Comment by pierrelouys** [comment]
Non-working download link
