### ISSUE TITLE
Can i help you ?

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#7]
★ PSP Hombrews Resources Sites.
May be Helpful

* https://www.psx-place.com/resources/categories/playstation-portable-psp.9/ PSP Resources - {PSX-Place}

* https://wololo.net/talk/viewtopic.php?f=47&t=8026 PSP Emulators Bible list - {Wololo}

* https://wololo.net/talk/viewtopic.php?f=2&t=1879 Signed Hombrews - {Wololo}

* https://wololo.net/talk/viewforum.php?f=2 PSP Hombrews Forums - {Wololo}

* http://psp-news.dcemu.co.uk/emulators-for-psp-1158256.html Emulators for PSP - {PSPNews}

* https://www.emu-land.net/portable/psp/emuls_for Emulators for PSP - {Emu-Land}

* http://psp-dev.org/hb/cat.html?c=Emu&p=6 - {PSPdev}

* http://www.emulator-zone.com/doc.php/psp/forthepsp.html Some Emulators list - {Emulator-zone}

* https://forums.ppsspp.org/showthread.php?tid=2616 PSP Hombrews Emulators Test - {PPSSPP forums}

* https://www.gopsp.it/index.php?showforum=14 PSP Hombrews Forums - {Gopsp forums}

* http://psphunt.blogspot.com/p/psp-hombrew-apps.html?m=1 Ultimate PSP Hombrews list - {PSPhunt}

[Helpful]
OK

**Comment by pierrelouys** [comment]
Hi RDX00, 
there are lots of untapped sources for homebrews still, just the project doesn't currently have the manpower to efficiently deal with them all. If you'd wish to join the archive, your contribution would be most welcome.

**Comment by ptnnx** [comment]
OK, pierrelouys I make a contribution

**Comment by ptnnx** [comment]
How can I connect this archive with you please help me. I will help you all.

**Comment by pierrelouys** [comment]
If you find any homebrew that is missing, you can open an issue here (as you have done now), and provide the link. I will be glad to upload any missing homebrews!
