### ISSUE TITLE
ADD+[NEW] Info

### ISSUE THREAD

**Issue by ptnnx** [PSP-Archive/docs#9]
**Hack/Cheats**

- Web cheats editor for snes9x TYL
https://github.com/yukinoraru/c4snes9xtyl

- PSP Cheat.db
https://github.com/Saramagrean/CWCheat-Database-Plus- Cheat.db+ Updated 2021 Version
* https://medium.com/@cksonlinebusiness/ppsspp-cheats-easy-step-by-step-guide-picture-video-c3132e6912d3 psp cheat how to use
* https://forums.ppsspp.org/showthread.php?tid=25656
* https://forums.ppsspp.org/showthread.php?tid=11961
* https://forums.ppsspp.org/showthread.php?tid=22800

- PSP Cheats guide
https://github.com/raing3/psp-cheat-guides/blob/master/ppsspp/creating-cheats-with-ppsspp/creating-cheats-with-ppsspp.md

- njemu .dat guide
https://www.elotrolado.net/hilo_manuales-de-juego-in-game-cps1-cps2-neo-geo_1565637#p1723624295

**Comment by ghost** [comment]
@RDX00 
Homebrew from brewology has been already been added, since the whole archive on archive.org is based on that site.
So you can ignore anything from brewology for the time being.

**Comment by ptnnx** [comment]
Ok

**Comment by ptnnx** [comment]
I try to Searching Missing PSP Hombrews.

**Comment by ghost** [comment]
@RDX00 
Pierre has already compiled a list of where to look for psp homebrew, you can check the list [here](https://docs.google.com/spreadsheets/d/11V_3Z18Va8iJxSsgaPAkEvirSF53O7oX40RvnBcEcNc/edit#gid=0) for a head start.

**Comment by pierrelouys** [comment]
Good suggestions, thanks! I removed the ngPSP duplicate. 
PSPKVM and OpenBOR are already available:

- https://archive.org/details/pspkvm.7z
- https://archive.org/details/open-bor.-7z

You can find the full file list in XML here: [link](https://archive.org/advancedsearch.php?q=collection%3Apsp-homebrew-library&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=description&fl[]=subject&fl[]=version&fl[]=date&fl[]=language&sort[]=titleSorter+asc&rows=10000&page=1&output=xml)

Will look at the other changes later today.

**Comment by ptnnx** [comment]
I could not find pspkvm & OpenBOR because both files are in game issue. Should be in the issue of emulator.
![IMG_20210407_173143](https://user-images.githubusercontent.com/81209454/113863461-4feab500-97c7-11eb-958c-066b4e2d5f28.jpg)

I Will Find missing? Hombrews in Various Resources. I Show XML file, future can be new missing file added.
Well, I am a finding.......

**Comment by pierrelouys** [comment]
About the old emus below (gpSP, VBA, etc) - I don't think it makes sense to archive mods and unofficial versions. Since they're only kept for historical interest (there are much better emus for all of those systems), I am currently keeping only the last official versions.

**Comment by RDX00** [comment]
VBA for PSP Remove because V004 broken icon error not open issue worth detail.
